version: '3.11'

services:
  app:
    build: .
    networks:
      caddy:
    labels:
      caddy: marechalantoine.fr
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true